/**
 * Lights Out on a 5x5 grid. Pressing a cell toggles it and its orthogonal
 * neighbors; the goal is to turn every light off. Puzzles are generated by
 * starting from all-off and applying a scramble of random presses, which
 * guarantees a solution exists (pressing the same sequence again undoes it,
 * since every cell's toggle is its own inverse) — a random board would not
 * have this guarantee.
 */
export const SIZE = 5;

export function emptyGrid(): boolean[] {
  return Array(SIZE * SIZE).fill(false);
}

export function toggleAt(grid: boolean[], cell: number): boolean[] {
  const next = [...grid];
  const row = Math.floor(cell / SIZE);
  const col = cell % SIZE;
  const targets = [
    [row, col],
    [row - 1, col],
    [row + 1, col],
    [row, col - 1],
    [row, col + 1],
  ];
  for (const [r, c] of targets) {
    if (r < 0 || r >= SIZE || c < 0 || c >= SIZE) continue;
    const i = r * SIZE + c;
    next[i] = !next[i];
  }
  return next;
}

export function randomPuzzle(pressCount = 15): boolean[] {
  let grid = emptyGrid();
  for (let i = 0; i < pressCount; i++) {
    grid = toggleAt(grid, Math.floor(Math.random() * grid.length));
  }
  return grid;
}

export function isSolved(grid: boolean[]): boolean {
  return grid.every((c) => !c);
}
