import type { QolFeatureGroup } from "@/lib/qol/features";

/**
 * Round three: 25 substantial, sitewide systems with three supporting
 * refinements each. The matching implementation lives in WebsiteIntelligence
 * and the website controls inside Settings.
 */
export const WEBSITE_INTELLIGENCE_FEATURES: readonly QolFeatureGroup[] = [
  {
    id: "page-guide",
    title: "Universal Page Guide",
    summary: "A consistent guide on every public page combines navigation, actions, insights and health checks.",
    category: "Navigate",
    enhancements: ["Route-aware page summary", "Three focused guide views", "Alt + I global shortcut"],
  },
  {
    id: "live-page-outline",
    title: "Live page outline",
    summary: "Long pages become scannable through an automatically generated outline of meaningful sections.",
    category: "Navigate",
    enhancements: ["H2 and H3 discovery", "Current-section highlighting", "One-click section scrolling"],
  },
  {
    id: "outline-search",
    title: "Outline search",
    summary: "Filter a dense page outline without using the browser's full-page find dialog.",
    category: "Discover",
    enhancements: ["Instant section filtering", "Clear-query action", "Helpful empty result state"],
  },
  {
    id: "section-deep-links",
    title: "Section deep links",
    summary: "Any discovered section can become a durable link for returning or sharing exact context.",
    category: "Organize",
    enhancements: ["Stable generated heading IDs", "Copy-section action", "Copied-state confirmation"],
  },
  {
    id: "reading-insights",
    title: "Page reading insights",
    summary: "Understand the size of a page before committing attention to it.",
    category: "Focus",
    enhancements: ["Estimated reading time", "Readable word count", "Live scroll completion"],
  },
  {
    id: "distraction-free-view",
    title: "Distraction-free view",
    summary: "Temporarily remove shared chrome and floating tools while keeping the current page intact.",
    category: "Focus",
    enhancements: ["Single-action entry", "Persistent exit control", "Escape-key recovery"],
  },
  {
    id: "smart-page-return",
    title: "Smart page return",
    summary: "Move back confidently with a safe home fallback when browser history is unavailable.",
    category: "Navigate",
    enhancements: ["History-aware back action", "Home fallback", "Recent-page shortcuts"],
  },
  {
    id: "universal-share-kit",
    title: "Universal share kit",
    summary: "Share any public destination in the format that suits the next conversation.",
    category: "Navigate",
    enhancements: ["Native device sharing", "Markdown-link copying", "Title and URL copying"],
  },
  {
    id: "route-refresh-controls",
    title: "Route refresh controls",
    summary: "Recover stale dynamic content without losing the current destination.",
    category: "Reliability",
    enhancements: ["Soft route refresh", "Full reload fallback", "Last-checked timestamp"],
  },
  {
    id: "page-health-audit",
    title: "Live page health audit",
    summary: "See the structural signals that make a page navigable, usable and supportable.",
    category: "Reliability",
    enhancements: ["Heading and link counts", "Control and form counts", "Image alternative-text check"],
  },
  {
    id: "support-snapshot",
    title: "Support snapshot",
    summary: "Create a privacy-safe technical summary when a page needs troubleshooting.",
    category: "Reliability",
    enhancements: ["Route and viewport context", "Connection and storage status", "One-click clipboard report"],
  },
  {
    id: "text-scale-profiles",
    title: "Website text scaling",
    summary: "Change interface text size independently from browser zoom using calibrated presets.",
    category: "Access",
    enhancements: ["90–120 percent range", "Instant live preview", "Device-local persistence"],
  },
  {
    id: "contrast-boost",
    title: "Contrast boost",
    summary: "Strengthen shared surfaces, muted text and focus indicators without changing the chosen theme.",
    category: "Access",
    enhancements: ["Stronger borders", "Clearer secondary text", "High-visibility focus rings"],
  },
  {
    id: "readable-font-mode",
    title: "Readable font mode",
    summary: "Switch reading content to a highly differentiated system typeface with calmer spacing.",
    category: "Access",
    enhancements: ["System-readable font stack", "Improved character spacing", "Game-board exclusions"],
  },
  {
    id: "large-cursor-mode",
    title: "Large cursor mode",
    summary: "Make pointer location easier to track across dense dashboards and game setup screens.",
    category: "Access",
    enhancements: ["High-contrast cursor", "Preserved text cursor", "Immediate global toggle"],
  },
  {
    id: "decorative-image-comfort",
    title: "Decorative image comfort",
    summary: "Reduce the visual dominance of nonessential imagery while preserving playable content.",
    category: "Comfort",
    enhancements: ["Gentle image dimming", "Hover and focus restoration", "Marked game-asset protection"],
  },
  {
    id: "external-link-clarity",
    title: "External link clarity",
    summary: "Destinations leaving Sam's Arcade become visually obvious before activation.",
    category: "Reliability",
    enhancements: ["External-link marker", "Domain tooltip", "Optional new-tab behavior"],
  },
  {
    id: "navigation-focus-recovery",
    title: "Navigation focus recovery",
    summary: "Keyboard and assistive-technology users arrive at page content after route changes.",
    category: "Access",
    enhancements: ["Main-content focus", "Scroll-safe behavior", "Route announcement coordination"],
  },
  {
    id: "keyboard-guide",
    title: "Keyboard guide",
    summary: "Power features explain their shortcuts where they are used instead of hiding them in documentation.",
    category: "Navigate",
    enhancements: ["Contextual shortcut labels", "Typing-field safeguards", "Escape handling"],
  },
  {
    id: "touch-feedback",
    title: "Touch feedback system",
    summary: "Buttons and links respond consistently on touch devices without waiting for navigation.",
    category: "Comfort",
    enhancements: ["Pressed-state animation", "Optional light haptics", "Reduced-motion compliance"],
  },
  {
    id: "mobile-safe-areas",
    title: "Mobile safe-area layout",
    summary: "Shared controls respect phone cutouts, home indicators and landscape edges.",
    category: "Comfort",
    enhancements: ["Bottom inset spacing", "Landscape side insets", "Dock collision prevention"],
  },
  {
    id: "form-draft-recovery",
    title: "Session form recovery",
    summary: "Eligible unsent text survives accidental navigation during the current browser tab.",
    category: "Reliability",
    enhancements: ["Session-only draft storage", "Private-route exclusions", "Automatic submit cleanup"],
  },
  {
    id: "unsaved-work-guard",
    title: "Unsaved work guard",
    summary: "Warn before closing a tab that contains an eligible unfinished form.",
    category: "Reliability",
    enhancements: ["Dirty-form detection", "Submit-state clearing", "Password and account exclusions"],
  },
  {
    id: "idle-power-pause",
    title: "Idle power pause",
    summary: "Decorative motion pauses while the tab is hidden and resumes cleanly on return.",
    category: "Performance",
    enhancements: ["Visibility-aware animation pause", "Automatic recovery", "No game-state mutation"],
  },
  {
    id: "clean-print-layout",
    title: "Clean print layout",
    summary: "Reference pages and game records print without navigation, floating tools or dark ink-heavy backgrounds.",
    category: "Performance",
    enhancements: ["Chrome-free output", "Readable light surfaces", "Expanded overflow content"],
  },
] as const;
