import type { QolFeatureGroup } from "@/lib/qol/features";

/**
 * Round two follows the same accounting promised to the player: one substantial
 * website system plus three supporting refinements. 25 groups × 4 = 100 more.
 */
export const WEBSITE_FEATURES: readonly QolFeatureGroup[] = [
  {
    id: "navigation-progress",
    title: "Navigation progress feedback",
    summary: "Every internal journey receives immediate visual feedback while the next screen prepares.",
    category: "Navigate",
    enhancements: ["Top-edge progress indicator", "Route-complete pulse", "Screen-reader page announcements"],
  },
  {
    id: "scroll-memory",
    title: "Per-page scroll memory",
    summary: "Long hubs and reference pages reopen near the exact place the player left them.",
    category: "Navigate",
    enhancements: ["Session-scoped position saving", "Automatic route restoration", "Reduced-motion-aware scrolling"],
  },
  {
    id: "back-to-top",
    title: "Smart back-to-top control",
    summary: "A contextual control makes long pages easy to escape without permanent screen clutter.",
    category: "Navigate",
    enhancements: ["Appears only after meaningful scrolling", "Smooth or instant motion preference", "Alt + Arrow Up shortcut"],
  },
  {
    id: "route-breadcrumbs",
    title: "Route-aware breadcrumbs",
    summary: "Understand location and jump upward through nested areas from a compact page trail.",
    category: "Navigate",
    enhancements: ["Human-readable route segments", "Direct ancestor links", "Copy-current-path action"],
  },
  {
    id: "page-toolkit",
    title: "Universal page toolkit",
    summary: "Common page actions stay available everywhere through one small, consistent dock.",
    category: "Navigate",
    enhancements: ["Copy deep link", "Fullscreen toggle", "Clean print action"],
  },
  {
    id: "page-notes",
    title: "Private page notes",
    summary: "Attach a device-local note to any route for training ideas, reminders or game plans.",
    category: "Organize",
    enhancements: ["Automatic per-route storage", "Live character count", "One-action note clearing"],
  },
  {
    id: "reading-ruler",
    title: "Pointer reading ruler",
    summary: "A subtle horizontal guide helps track dense text and tables without capturing input.",
    category: "Access",
    enhancements: ["Pointer-follow positioning", "Non-interactive overlay", "Instant global toggle"],
  },
  {
    id: "focus-spotlight",
    title: "Focus spotlight",
    summary: "Dim peripheral content and keep the current pointer area visually prominent.",
    category: "Access",
    enhancements: ["Live pointer spotlight", "Soft peripheral dimming", "Works alongside keyboard focus rings"],
  },
  {
    id: "link-clarity",
    title: "Enhanced link clarity",
    summary: "Make destinations unmistakable for players who prefer stronger non-colour cues.",
    category: "Access",
    enhancements: ["Persistent content-link underlines", "Thicker hover treatment", "High-visibility keyboard focus"],
  },
  {
    id: "large-targets",
    title: "Large interaction targets",
    summary: "Increase shared buttons, fields and controls toward touch-friendly dimensions.",
    category: "Access",
    enhancements: ["44-pixel minimum controls", "Roomier form fields", "Mobile-safe action spacing"],
  },
  {
    id: "solid-surfaces",
    title: "Reduced-transparency surfaces",
    summary: "Replace translucent layers with calmer opaque panels for easier visual separation.",
    category: "Access",
    enhancements: ["Backdrop blur removal", "Opaque navigation surfaces", "Stronger dialog separation"],
  },
  {
    id: "grayscale-review",
    title: "Grayscale review mode",
    summary: "Temporarily remove colour to check visual hierarchy or reduce colour distraction.",
    category: "Access",
    enhancements: ["Single-switch page filter", "Preserved focus outlines", "No permanent theme mutation"],
  },
  {
    id: "content-width",
    title: "Adaptive reading width",
    summary: "Choose narrow, standard or wide content rhythm without changing game-board sizing.",
    category: "Comfort",
    enhancements: ["Three width presets", "Text-focused route targeting", "Instant persisted application"],
  },
  {
    id: "reading-spacing",
    title: "Reading spacing controls",
    summary: "Tune paragraph line height and letter spacing independently from overall text size.",
    category: "Comfort",
    enhancements: ["Compact, comfortable and relaxed lines", "Normal or wide tracking", "Paragraph-scoped styling"],
  },
  {
    id: "calm-visuals",
    title: "Calm visual mode",
    summary: "Reduce decorative intensity while preserving the arcade's identity and information hierarchy.",
    category: "Comfort",
    enhancements: ["Simplified page gradients", "Quieter shadows", "Decorative pulse suppression"],
  },
  {
    id: "session-clock",
    title: "Visible session clock",
    summary: "Track active time on Sam's Arcade without counting time spent in another tab.",
    category: "Focus",
    enhancements: ["Visibility-aware timing", "Compact floating display", "One-click session reset"],
  },
  {
    id: "break-reminders",
    title: "Healthy break reminders",
    summary: "Choose a play interval and receive a respectful reminder without interrupting a game.",
    category: "Focus",
    enhancements: ["25, 45 and 60 minute intervals", "Dismissible reminder", "Automatic timer restart"],
  },
  {
    id: "website-presets",
    title: "Website preference presets",
    summary: "Apply coordinated reading, visibility or efficiency choices in a single action.",
    category: "Personalize",
    enhancements: ["Reading preset", "Visibility preset", "Performance preset"],
  },
  {
    id: "device-preferences",
    title: "Device-local website profile",
    summary: "Website preferences persist privately on the current device and join existing QOL exports.",
    category: "Personalize",
    enhancements: ["Automatic local saving", "Validated import compatibility", "Dedicated reset control"],
  },
  {
    id: "low-data-mode",
    title: "Manual low-data mode",
    summary: "Reduce decorative rendering and background effects when bandwidth or hardware is limited.",
    category: "Performance",
    enhancements: ["Nonessential animation suppression", "Lighter surface effects", "Visible active-state badge"],
  },
  {
    id: "automatic-data-saver",
    title: "Connection-aware data saver",
    summary: "Respond to browser connection hints when a slow or metered network is detected.",
    category: "Performance",
    enhancements: ["Save-Data detection", "Slow-connection detection", "Manual override remains available"],
  },
  {
    id: "battery-awareness",
    title: "Battery-aware interface",
    summary: "Reduce visual workload automatically when a supported device reports low battery.",
    category: "Performance",
    enhancements: ["Low-battery detection", "Charging-state recovery", "Privacy-safe local processing"],
  },
  {
    id: "low-power-rendering",
    title: "Low-power rendering profile",
    summary: "Coordinate motion, blur and shadow reductions rather than applying isolated micro-tweaks.",
    category: "Performance",
    enhancements: ["Animation throttling", "Backdrop-filter removal", "Shadow simplification"],
  },
  {
    id: "page-health",
    title: "Page health dashboard",
    summary: "See the browser capabilities that affect reliability before assuming the website is broken.",
    category: "Reliability",
    enhancements: ["Network state", "Storage availability", "Power and data-saver status"],
  },
  {
    id: "recovery-toolkit",
    title: "Self-service recovery toolkit",
    summary: "Resolve common client-side issues from one safe panel without touching account data.",
    category: "Reliability",
    enhancements: ["Clean page reload", "Copy diagnostic summary", "Reset website preferences only"],
  },
] as const;
